config/routes.rb
Rails.application.routes.draw do
  resources :wines
  root 'wines#index'
  get 'load_catalog', to: 'wine_dot_com#load_catalog'
  delete 'dump_catalog', to: 'wine_dot_com#dump_catalog'
  get 'dashboard', to: 'pages#dashboard'
end

app/models/appellation.rb
class Appellation
  include Mongoid::Document
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  field :api_id, type: Integer
  field :name, type: String
  field :region, type: String

  index({ api_id: 1}, { unique: true })

  has_many :wines

  validates_presence_of :api_id, :name, :region
  validates_numericality_of :api_id

  def as_indexed_json
    as_json(except: [:id, :_id])
  end
end

app/models/varietal.rb
class Varietal
  include Mongoid::Document
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  field :api_id, type: Integer
  field :name, type: String
  field :type, type: String

  index({ api_id: 1}, { unique: true })

  has_many :wines

  validates_presence_of :api_id, :name, :type
  validates_numericality_of :api_id

  def as_indexed_json
    as_json(except: [:id, :_id])
  end
end

app/models/wine.rb
class Wine
  include Mongoid::Document
  field :api_id, type: Integer
  field :name, type: String
  field :price_retail, type: Money
  field :search_terms, type: String

  index({ api_id: 1}, { unique: true })

  belongs_to :appellation
  belongs_to :varietal

  validates_presence_of :name
  validates_numericality_of :price_retail

  before_save do |document|
    attributes = [
      document.name,
      document.appellation.try(:name),
      document.appellation.try(:region),
      document.varietal.try(:name),
      document.varietal.try(:type)
    ]
    document.search_terms = attributes.compact.join(' ')
  end

  def self.search(search_terms)
    Wine.where(search_terms: search_to_regex(search_terms))
  end

  def self.search_to_regex(search_terms)
    Regexp.new(search_terms.split.map {|term| "(?=.*#{term})" }.join.concat(".*"), "i")
  end
end

app/models/wine_dot_com.rb
class WineDotCom
  include HTTParty
  base_uri ENV['WINE_URL']

  def initialize(records)
    @records = records
    @size = records > 100 ? 100 : records
    @offset = 1
  end

  def catalog
    options = { query: {size: @size, offset: @offset, apikey: ENV['WINE_KEY']} }
    self.class.get("/catalog", options)
  end

  def load_catalog
    while @records > 0
      response = self.catalog
      response['Products']['List'].each do |record|
        next unless record_valid?(record)
        attributes = wine_attributes(record, appellation_for(record), varietal_for(record))
        if wine = Wine.find_by(api_id: attributes[:api_id])
          wine.update(attributes)
        else
          Wine.create(attributes)
        end
      end
      @records -= @size
      @offset += @size
      @size = @size > @records ? @records : @size
    end
  end

  def record_valid?(record)
    record['Type'] == 'Wine' &&
      record['Id'].try(:present?) &&
      record['Name'].try(:present?) &&
      record['PriceRetail'].try(:present?)
  end

  def wine_attributes(record, appellation, varietal)
    {
      api_id: record['Id'],
      name: record['Name'],
      price_retail: record['PriceRetail'],
      appellation: appellation,
      varietal: varietal
    }
  end

  def appellation_for(record)
    return nil unless record['Appellation']['Id'].present?
    attributes = {
      api_id: record['Appellation']['Id'],
      name: record['Appellation']['Name'],
      region: record['Appellation']['Region']['Name']
    }
    if appellation = Appellation.find_by(api_id: attributes[:api_id])
      appellation.update(attributes)
    else
      appellation = Appellation.create(attributes)
    end
    appellation
  end

  def varietal_for(record)
    return nil unless record['Varietal']['Id'].present?
    attributes = {
      api_id: record['Varietal']['Id'],
      name: record['Varietal']['Name'],
      type: record['Varietal']['WineType']['Name']
    }
    if varietal = Varietal.find_by(api_id: attributes[:api_id])
      varietal.update(attributes)
    else
      varietal = Varietal.create(attributes)
    end
    varietal
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
  end
end

app/controllers/wine_dot_com_controller.rb
class WineDotComController < ApplicationController
  def load_catalog
    LoadCatalogJob.perform_later(params[:records].to_i)
    @notice = "Wine.com records being added to database."
  end

  def dump_catalog
    DumpCatalogJob.perform_later
    @notice = "Wine.com records being removed from database."
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [:show, :edit, :update, :destroy]

  def index
    if search_terms = params[:search]
      @wines = Wine.search(search_terms).page(params[:page]).per(15)
    else
      @wines = Wine.page(params[:page]).per(15)
    end
  end

  def show
  end

  def new
    @wine = Wine.new
  end

  def edit
  end

  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: 'Wine was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: 'Wine was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: 'Wine was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wine_params
      params.require(:wine).permit(:name, :price_retail, :appellation_id, :varietal_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_notice.html.erb
<p id="notice"><%= notice %></p>

app/views/layouts/_top_bar.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><%= link_to 'Sommelier', root_path %></li>
      <li><%= link_to 'Wines', wines_path %></li>
      <li><%= link_to 'Dashboard', dashboard_path%></li>
    </ul>
  </div>
</div>

app/views/layouts/_wine_dot_com_logo.html.erb
<a href="http://www.wine.com/" title="Wine.com the destination for Wine and Wine Gifts">
  <img src="http://cache.wine.com/images/logos/80x20_winecom_logo.png" alt="Wine.com the destination for Wine and Wine Gifts" />
</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Sommelier" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/top_bar'%>

    <div class="content row">
      <div class="small-12 columns">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class='flash-notice'></div>
<h1>Dashboard</h1>
<hr>
<h3>Wine.com API</h3>
<div class="row">
  <div class="small-12 large-6 columns">
    <div class='load-catalog'>
      <%= render 'wine_dot_com/load_catalog_form' %>
    </div>
  </div>
  <div class="small-12 large-6 columns">
    <div class='dump-catalog'>
      <%= link_to 'Remove records', dump_catalog_path, method: :delete, remote: true, data: { confirm: 'Are you sure? This cannot be undone.' }, class: 'button' %>
    </div>
  </div>
</div>

app/views/wine_dot_com/_load_catalog_form.html.erb
<form action="/load_catalog" method="GET" data-remote="true">
  <div class="input-group">
    <span class="input-group-label">Load records</span>
    <input class="input-group-field" type="number" id="records" name="records" value="500">
    <div class="input-group-button">
      <input type="submit" class="button" value="Submit">
    </div>
  </div>
</form>

app/views/wine_dot_com/dump_catalog.js.erb
$('.flash-notice').html('<%= j render partial: "layouts/flash_notice", locals: {notice: @notice} %>');

app/views/wine_dot_com/index.html.erb
Loading wines. This may take a minute

app/views/wine_dot_com/load_catalog.js.erb
$('.flash-notice').html('<%= j render partial: "layouts/flash_notice", locals: {notice: @notice} %>');
$('.load-catalog').html('<%= j render("wine_dot_com/load_catalog_form") %>')

app/views/wines/_form.html.erb
<%= form_for(@wine) do |f| %>
  <% if @wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% @wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price_retail %><br>
    <%= f.text_field :price_retail %>
  </div>
  <div class="field">
    <%= f.label :appellation_id %><br />
    <%= f.collection_select :appellation_id, Appellation.all, :id, :name, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :varietal_id %><br />
    <%= f.collection_select :varietal_id, Varietal.all, :id, :name, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit class: 'button'%>
  </div>
<% end %>

app/views/wines/_search.html.erb
<div class="input-group" id='wine-search-form' data-path=<%= wines_path %>>
  <span class="input-group-label">Search</span>
  <%= text_field_tag 'wine-search-input', params[:search], class: "input-group-field"  %>
</div>

app/views/wines/_wine.html.erb
<tr>
  <td><%= link_to wine.name, wine %></td>
  <td><%= wine.price_retail %></td>
  <td><%= wine.appellation.try(:name) %></td>
  <td><%= wine.appellation.try(:region) %></td>
  <td><%= wine.varietal.try(:name) %></td>
  <td><%= wine.varietal.try(:type) %></td>
</tr>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form' %>

<div class="button-group">
  <%= link_to 'Show', @wine %>
  <%= link_to 'Back', wines_path, class: 'button' %>
</div>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines <%= render 'layouts/wine_dot_com_logo' %></h1>

<div class="row">
  <div class="small-12 medium-6 columns">
    <%= link_to 'New Wine', new_wine_path, class: 'button' %>
  </div>
  <div class="small-12 medium-6 columns">
    <%= render 'search' %>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price retail</th>
      <th>Appellation</th>
      <th>Region</th>
      <th>Varietal</th>
      <th>Type</th>
    </tr>
  </thead>

  <tbody id="wines">
    <%= render partial: 'wine', collection: @wines %>
  </tbody>
</table>

<div id='wines-paginator'>
  <%= paginate @wines, :remote => true %>
</div>

app/views/wines/index.js.erb
$('#wines').html('<%= j render partial: "wine", collection: @wines %>');
$('#wines-paginator').html('<%= j paginate @wines, :remote => true %>');

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form' %>

<%= link_to 'Back', wines_path, class: 'button' %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @wine.name %></h2>

<p>
  <strong>Price retail:</strong>
  <%= @wine.price_retail %>
</p>

<% if @wine.appellation %>
  <p>
    <strong>Appellation:</strong>
    <%= @wine.appellation.name %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= @wine.appellation.region %>
  </p>
<% end %>

<% if @wine.varietal %>
  <p>
    <strong>Varietal:</strong>
    <%= @wine.varietal.name %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= @wine.varietal.type %>
  </p>
<% end %>

<div class="button-group">
  <%= link_to 'Edit', edit_wine_path(@wine), class: 'button' %>
  <%= link_to 'Back', wines_path, class: 'button' %>
  <%= link_to 'Destroy', @wine, method: :delete, data: { confirm: 'Are you sure?' }, class: 'alert button' %>
</div>